#!/bin/bash

docker-compose up -d

rm -rf deps

docker-compose exec application mkdir deps
docker-compose exec application touch /app/deps/test

echo "Files in the container"
docker-compose exec application ls

echo "Files in the host"
ls deps

docker-compose stop
